# Generated by Django 2.2.6 on 2019-10-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_kullanıcı_cevabı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='dogru_cevap',
            field=models.CharField(max_length=10),
        ),
    ]
