# Generated by Django 2.2.6 on 2019-11-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20191111_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_question',
            old_name='a',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='account_question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
