# Generated by Django 2.2.6 on 2019-11-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191026_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
