# Generated by Django 3.0.3 on 2020-02-23 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_test_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='test_start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
