# Generated by Django 3.0.3 on 2020-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='test_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
